version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'khenda123456'
      MYSQL_ROOT_PASSWORD: 'khendaroot123456'
      MYSQL_DATABASE: 'khenda'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    #volumes:
      #- ./db_data:/var/lib/mysql
  app:
    build: .
    environment:
      MYSQL_CONNECTION: 'db'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'khenda123456'
      MYSQL_DATABASE: 'khenda'
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - db